/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ButtonRadio: typeof import('./src/components/ButtonRadio.vue')['default']
    ChoosePerson: typeof import('./src/components/ChoosePerson.vue')['default']
    CollapseItem: typeof import('./src/components/CollapseItem.vue')['default']
    CommonSelect: typeof import('./src/components/CommonSelect.vue')['default']
    CommonUpload: typeof import('./src/components/CommonUpload.vue')['default']
    DateSelect: typeof import('./src/components/DateSelect.vue')['default']
    Group: typeof import('./src/components/Group.vue')['default']
    HeadeBar: typeof import('./src/components/HeadeBar.vue')['default']
    IconFont: typeof import('./src/components/IconFont.vue')['default']
    LangChange: typeof import('./src/components/LangChange.vue')['default']
    Mytable: typeof import('./src/components/Mytable.vue')['default']
    ReadNFC: typeof import('./src/components/ReadNFC.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
    VanBadge: typeof import('vant/es')['Badge']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanDialog: typeof import('vant/es')['Dialog']
    VanDropdownItem: typeof import('vant/es')['DropdownItem']
    VanDropdownMenu: typeof import('vant/es')['DropdownMenu']
    VanField: typeof import('vant/es')['Field']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanList: typeof import('vant/es')['List']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPicker: typeof import('vant/es')['Picker']
    VanPopup: typeof import('vant/es')['Popup']
    VanPullRefresh: typeof import('vant/es')['PullRefresh']
    VanSearch: typeof import('vant/es')['Search']
    VanSignature: typeof import('vant/es')['Signature']
    VanSticky: typeof import('vant/es')['Sticky']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanTab: typeof import('vant/es')['Tab']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTabs: typeof import('vant/es')['Tabs']
    VanTextEllipsis: typeof import('vant/es')['TextEllipsis']
    WriteNFC: typeof import('./src/components/WriteNFC.vue')['default']
  }
}
